-- 게시판 테이블 생성
CREATE TABLE BBS
(
    BBS_ID     NUMBER(3) PRIMARY KEY,
    BBS_NAME   VARCHAR2(20),
    BBS_SBJ    VARCHAR2(80),
    BBS_CTT    VARCHAR2(300),
    BBS_DATE   DATE      DEFAULT SYSDATE,
    BBS_HIT    NUMBER(3) DEFAULT 0,
    BBS_GROUP  NUMBER(3),
    BBS_STEP   NUMBER(3),
    BBS_INDENT NUMBER(3)
);

-- 게시판 테이블 Comment 설정
--COMMENT ON TABLE [테이블명] IS [Comment];
COMMENT ON TABLE BBS IS '게시판';

-- 게시판 테이블 컬럼 Comment 설정
--COMMENT ON COLUMN [테이블명].[컬럼명] IS '[Comment]';
COMMENT ON COLUMN BBS.BBS_ID IS '게시판 고유 아이디';
COMMENT ON COLUMN BBS.BBS_NAME IS '게시글 작성자명';
COMMENT ON COLUMN BBS.BBS_SBJ IS '게시글 제목';
COMMENT ON COLUMN BBS.BBS_CTT IS '게시글 내용';
COMMENT ON COLUMN BBS.BBS_DATE IS '게시글 등록일';
COMMENT ON COLUMN BBS.BBS_HIT IS '게시글 조회수';
COMMENT ON COLUMN BBS.BBS_GROUP IS '게시글 그룹';
COMMENT ON COLUMN BBS.BBS_STEP IS '게시글 답변 위치';
COMMENT ON COLUMN BBS.BBS_INDENT IS '게시글 답변 Depth';

-- 게시판 테이블 시퀀스 생성
CREATE SEQUENCE SEQ_BBS;

COMMIT;


-- 시퀀스 조회
SELECT *
FROM USER_SEQUENCES;


-- 카드결제 테이블 생성
CREATE TABLE CARD
(
    USER_NAME VARCHAR2(20),
    AMOUNT    NUMBER(3)
);

-- 카드결제 테이블 Comment 설정
COMMENT ON TABLE CARD IS '카드결제';

-- 카드결제 테이블 컬럼 Comment 설정
COMMENT ON COLUMN CARD.USER_NAME IS '결제자';
COMMENT ON COLUMN CARD.AMOUNT IS '금액';


-- 티켓 테이블 생성
CREATE TABLE TICKET
(
    USER_NAME VARCHAR2(20),
    CNT       NUMBER(3)
        CONSTRAINT CNT_CK CHECK ( CNT < 6 )
);

-- 티켓 테이블 Comment 설정
COMMENT ON TABLE TICKET IS '티켓';

-- 티켓 테이블 컬럼 Comment 설정
COMMENT ON COLUMN TICKET.USER_NAME IS '티켓 구매자';
COMMENT ON COLUMN TICKET.CNT IS '티켓 수';

COMMIT;


-- 회원 테이블 생성
CREATE TABLE MEMBER
(
    ID    VARCHAR2(20) NOT NULL PRIMARY KEY,
    PWD   VARCHAR2(20) NOT NULL,
    NAME  VARCHAR2(20) NOT NULL,
    TEL   VARCHAR2(13) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL
);

-- 회원 테이블 Comment 설정
COMMENT ON TABLE MEMBER IS '회원';

-- 회원 테이블 컬럼 Comment 설정
COMMENT ON COLUMN MEMBER.ID IS '아이디';
COMMENT ON COLUMN MEMBER.PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.NAME IS '이름';
COMMENT ON COLUMN MEMBER.TEL IS '연락처';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';

COMMIT;