package com.udemy.spring.practical.mbgmember.vo;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDEMY.MEMBER.ID
     *
     * @mbg.generated Fri Feb 19 15:46:14 KST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDEMY.MEMBER.PWD
     *
     * @mbg.generated Fri Feb 19 15:46:14 KST 2021
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDEMY.MEMBER.NAME
     *
     * @mbg.generated Fri Feb 19 15:46:14 KST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDEMY.MEMBER.TEL
     *
     * @mbg.generated Fri Feb 19 15:46:14 KST 2021
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDEMY.MEMBER.EMAIL
     *
     * @mbg.generated Fri Feb 19 15:46:14 KST 2021
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDEMY.MEMBER.ID
     *
     * @return the value of UDEMY.MEMBER.ID
     *
     * @mbg.generated Fri Feb 19 15:46:14 KST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDEMY.MEMBER.ID
     *
     * @param id the value for UDEMY.MEMBER.ID
     *
     * @mbg.generated Fri Feb 19 15:46:14 KST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDEMY.MEMBER.PWD
     *
     * @return the value of UDEMY.MEMBER.PWD
     *
     * @mbg.generated Fri Feb 19 15:46:14 KST 2021
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDEMY.MEMBER.PWD
     *
     * @param pwd the value for UDEMY.MEMBER.PWD
     *
     * @mbg.generated Fri Feb 19 15:46:14 KST 2021
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDEMY.MEMBER.NAME
     *
     * @return the value of UDEMY.MEMBER.NAME
     *
     * @mbg.generated Fri Feb 19 15:46:14 KST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDEMY.MEMBER.NAME
     *
     * @param name the value for UDEMY.MEMBER.NAME
     *
     * @mbg.generated Fri Feb 19 15:46:14 KST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDEMY.MEMBER.TEL
     *
     * @return the value of UDEMY.MEMBER.TEL
     *
     * @mbg.generated Fri Feb 19 15:46:14 KST 2021
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDEMY.MEMBER.TEL
     *
     * @param tel the value for UDEMY.MEMBER.TEL
     *
     * @mbg.generated Fri Feb 19 15:46:14 KST 2021
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDEMY.MEMBER.EMAIL
     *
     * @return the value of UDEMY.MEMBER.EMAIL
     *
     * @mbg.generated Fri Feb 19 15:46:14 KST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDEMY.MEMBER.EMAIL
     *
     * @param email the value for UDEMY.MEMBER.EMAIL
     *
     * @mbg.generated Fri Feb 19 15:46:14 KST 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }
}